escapefrom162: escapefrom162.cpp instructor.o ta.o intrepidstudent.o openspace.o wall.o mazelevel.o maze.o mazeperson.hpp mazelocation.hpp
	g++ escapefrom162.cpp instructor.o ta.o intrepidstudent.o openspace.o wall.o mazelevel.o maze.o -o escapefrom162

instructor.o: instructor.cpp instructor.hpp
	g++ -c instructor.cpp
ta.o: ta.cpp ta.hpp
	g++ -c ta.cpp
intrepidstudent.o: intrepidstudent.cpp intrepidstudent.hpp
	g++ -c intrepidstudent.cpp
openspace.o: openspace.cpp openspace.hpp
	g++ -c openspace.cpp
wall.o: wall.cpp wall.hpp
	g++ -c wall.cpp
mazelevel.o: mazelevel.cpp mazelevel.hpp
	g++ -c mazelevel.cpp
maze.o: maze.cpp maze.hpp
	g++ -c maze.cpp


