zoo_tyoon: zoo_tycoon.cpp animal.o game.o monkey.o sloth.o sea_otter.o
	g++ zoo_tycoon.cpp animal.o game.o monkey.o sloth.o sea_otter.o -o zoo_tycoon
game.o: game.cpp game.hpp
	g++ -c game.cpp
animal.o: animal.cpp animal.hpp
	g++ -c animal.cpp
monkey.o: monkey.cpp monkey.hpp
	g++ -c monkey.cpp
sloth.o: sloth.cpp sloth.hpp
	g++ -c sloth.cpp
sea_otter.o: sea_otter.cpp sea_otter.hpp
	g++ -c sea_otter.cpp




